# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bookerpro_development

test:
  <<: *default
  database: bookerpro_test

production:
  <<: *default
  database: bookerpro_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>